### ISSUE TITLE
Controller node flagged as NotReady and containerd gets "Can't convert 1(int64) to float64" error

### ISSUE THREAD

**Issue by beraldoleal** [confidential-containers/operator#305] opened 2023-12-14 16:18 UTC
**Describe the bug**

Trying to bootstrap operator && ccruntime (main) but Worker nodes moves into NotReady state. Containerd logs shows "Can't convert 1(int64) to float64"

Pods are running (and maybe that is the reason CI is passing), but worker node goes into "NotReady" state:
 
```
$ kubectl get nodes
NAME                   STATUS     ROLES           AGE   VERSION
peer-pods-ctlplane-0   Ready      control-plane   60m   v1.26.7
peer-pods-worker-0     NotReady   worker          56m   v1.26.7
```

Describing the node, shows:

```
$ kubectl describe node peer-pods-worker-0 | tail -f
  memory             210Mi (1%)  150Mi (0%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-1Gi      0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
Events:
  Type     Reason             Age                   From     Message
  ----     ------             ----                  ----     -------
  Normal   NodeNotReady       59m                   kubelet  Node peer-pods-worker-0 status is now: NodeNotReady
  Warning  ContainerGCFailed  59m                   kubelet  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/containerd/containerd.sock: connect: no such file or directory"
  Warning  ImageGCFailed      4m14s (x11 over 54m)  kubelet  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/containerd/containerd.sock: connect: no such file or directory"
```

Full [containerd log](https://pastebin.com/raw/gd7Phrg9) is here.

**To Reproduce**
Steps to reproduce the behaviour:

1. Install a k8s cluster
2. kubectl apply -k "github.com/confidential-containers/operator/config/default"
3. kubectl apply -k "github.com/confidential-containers/operator/config/samples/ccruntime/peer-pods"
4. kubectl get nodes

**Describe the results you expected**

WorkerNode in Running state.

**Describe the results you received:**

See errors above.

**Comment by stevenhorsman** [comment] 2023-12-14 16:29
@BbolroC has an error on the nightly s390x test since yesterday at well. @wainersm @ldoktor - do you think that we should re-instate the nightly operator test on GHA now like we had on jenkins to hoepfullly spot issues sooner?

Choi tested out commit kata-containers-ee74fca92cf0db32e52918ac418357a58b53f2c9 which seemed to work, so I guess there is something that went into kata-containers in the last ~36/48 hours that is causing the issue (maybe the tomlq containerd issue).

In the short-term if people want a workaround they can update the payload to use the `kata-containers-ee74fca92cf0db32e52918ac418357a58b53f2c9-amd64` tage rather than latest and that should work.

**Comment by stevenhorsman** [comment] 2023-12-14 16:54
I've tested tag `kata-containers-dfaf006fccd5f09b665a3a9178105480a5bed810-amd64` and that seems to work:
```
# kubectl get pods -A
NAMESPACE                        NAME                                                     READY   STATUS    RESTARTS   AGE
confidential-containers-system   cc-operator-controller-manager-ccbbcfdf7-bbsxh           2/2     Running   0          2m8s
confidential-containers-system   cc-operator-daemon-install-q5spn                         1/1     Running   0          106s
confidential-containers-system   cc-operator-pre-install-daemon-f9knw                     1/1     Running   0          114s
kube-flannel                     kube-flannel-ds-65k94                                    1/1     Running   0          11m
kube-system                      coredns-6d4b75cb6d-9d4pg                                 1/1     Running   0          11m
kube-system                      coredns-6d4b75cb6d-fp8cl                                 1/1     Running   0          11m
kube-system                      etcd-sh-operator-main1.fyre.ibm.com                      1/1     Running   1          11m
kube-system                      kube-apiserver-sh-operator-main1.fyre.ibm.com            1/1     Running   1          11m
kube-system                      kube-controller-manager-sh-operator-main1.fyre.ibm.com   1/1     Running   1          11m
kube-system                      kube-proxy-jjf6s                                         1/1     Running   0          11m
kube-system                      kube-scheduler-sh-operator-main1.fyre.ibm.com            1/1     Running   1          11m
root@sh-operator-main1:~/go/src/github.com/confidential-containers/operator/tests/e2e# kubectl describe pod cc-operator-daemon-install-q5spn -n confidential-containers-system
Name:         cc-operator-daemon-install-q5spn
...
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  2m9s  default-scheduler  Successfully assigned confidential-containers-system/cc-operator-daemon-install-q5spn to sh-operator-main1.fyre.ibm.com
  Normal  Pulling    2m8s  kubelet            Pulling image "quay.io/kata-containers/kata-deploy-ci:kata-containers-dfaf006fccd5f09b665a3a9178105480a5bed810-amd64"
  Normal  Pulled     2m7s  kubelet            Successfully pulled image "quay.io/kata-containers/kata-deploy-ci:kata-containers-dfaf006fccd5f09b665a3a9178105480a5bed810-amd64" in 580.280583ms
  Normal  Created    2m7s  kubelet            Created container cc-runtime-install-pod
  Normal  Started    2m7s  kubelet            Started container cc-runtime-install-pod
```

**Comment by stevenhorsman** [comment] 2023-12-14 17:02
tag `kata-containers-6c2e2a9120126db7d4620c3cf51ecc1fec099535-amd64` did not work

**Comment by stevenhorsman** [comment] 2023-12-14 17:35
tag `kata-containers-a998e89bcf87d7bd5763544bb5fe7997c9a67f9e-amd64` seems to fail too, so I've narrowed it down to commits as much as I can.

**Comment by stevenhorsman** [comment] 2023-12-14 17:40
In `journalctl -u containerd` I found:
```
Dec 14 09:39:42 sh-operator-main1.fyre.ibm.com containerd[1288457]: containerd: (204, 1): Can't convert 1(int64) to float64
```
which I guess might be the cause

**Comment by wainersm** [comment] 2023-12-14 17:40
> @BbolroC has an error on the nightly s390x test since yesterday at well. @wainersm @ldoktor - do you think that we should re-instate the nightly operator test on GHA now like we had on jenkins to hoepfullly spot issues sooner?
>

@stevenhorsman yes, I'm 100% in having nightly jobs. Created an issue for that: https://github.com/confidential-containers/operator/issues/306

> Choi tested out tag kata-containers-ee74fca92cf0db32e52918ac418357a58b53f2c9 which seemed to work, so I guess there is something that went into kata-containers in the last ~36/48 hours that is causing the issue (maybe the tomlq containerd issue).
> 
> In the short-term if people want a workaround they can update the payload to use the `kata-containers-ee74fca92cf0db32e52918ac418357a58b53f2c9-amd64` tage rather than latest and that should work.

I'm not sure this is a recent regression or introduced by the time we switched to kata-runtime main. @stevenhorsman do you remember if we ran some function tests by that time?

I'm asking because the current operator tests (install, uninstall, reinstall) can't catch such as error because they are only checking if `cc-operator-daemon-install` and `cc-operator-pre-install-daemon` are `running` (which is the case). It might be a bug on the `cc-operator-pre-install-daemon` as well that doesn't return error when the restart of containerd fails. Anyway, the operator tests should be doing more checks as, for example, whether the worker is still "ready" after the installation/uninstallation

**Comment by stevenhorsman** [comment] 2023-12-14 17:42
@wainersm - I'm pretty sure it is related to the tomlq changes that went in, and trying to narrow down on the specific error. It's not related to the switch to main - as I linked above the nightly tests yesterday morning worked fine.

**Comment by wainersm** [comment] 2023-12-14 17:43
> In `journalctl -u containerd` I found:
> 
> ```
> Dec 14 09:39:42 sh-operator-main1.fyre.ibm.com containerd[1288457]: containerd: (204, 1): Can't convert 1(int64) to float64
> ```
> 
> which I guess might be the cause

On Beraldo's environment we reverted containerd's configuration.toml to defaults (`containerd config default`) and then it restarted correctly. It is indeed a malformed configuration.toml file which driving the fail.

**Comment by stevenhorsman** [comment] 2023-12-14 17:47
I think the error might be that we have:
```
sampling_ratio = 1
```
which should be a float?

**Comment by stevenhorsman** [comment] 2023-12-14 17:47
I am curious as how the kata-deploy tests aren't failing too?

**Comment by wainersm** [comment] 2023-12-14 17:48
> @wainersm - I'm pretty sure it is related to the tomlq changes that went in, and trying to narrow down on the specific error. It's not related to the switch to main - as I linked above the nightly tests yesterday morning worked fine.

yeah, it seems to be related with 'tomlq'. The failed nightly for s390x (http://jenkins.katacontainers.io/view/all/job/confidential-containers-operator-main-ubuntu-20.04-s390x-SE-daily/266/console) had the uninstall test failing. Maybe we got "lucky" to catch the error because the tests aren't doing enough checks.

Question to the future: why it passed on kata CI? :D

**Comment by wainersm** [comment] 2023-12-14 17:50
> I think the error might be that we have:
> 
> ```
> sampling_ratio = 1
> ```
> 
> which should be a float?

hmmm maybe... @beraldoleal found a bug (and fix) on containerd regarding a conversion from int to float too. @beraldoleal could you share the link? But it might be an old bug on another piece of containerd's code...

**Comment by stevenhorsman** [comment] 2023-12-14 17:58
> I think the error might be that we have:
>
>`sampling_ratio = 1`
> which should be a float?

I checked a working version and it has:
```
[plugins."io.containerd.internal.v1.tracing"]
sampling_ratio=1.0
service_name="containerd"
```

as the main difference, so we need to understand why tomlq is updating that next I guess and fix it in kata

**Comment by stevenhorsman** [comment] 2023-12-14 18:05
Running `tomlq -i -t '.debug.level = "debug"' config.toml` leads to a diff of:
```
212c166
< sampling_ratio = 1
---
>     sampling_ratio = 1.0
272a227
```

(tomlq also updates all the whitespace which is annoying. So we either need to find a way to stop that, or revert the PR in kata until we can fix in in tomlq. I think the net outcome is that this is a kata defect related to https://github.com/kata-containers/kata-containers/pull/8639/files and so should be raised as a kata issue.

**Comment by wainersm** [comment] 2023-12-14 18:10
> Running `tomlq -i -t '.debug.level = "debug"' config.toml` leads to a diff of:
> 
> ```
> 212c166
> < sampling_ratio = 1
> ---
> >     sampling_ratio = 1.0
> 272a227
> ```
> 
> (tomlq also updates all the whitespace which is annoying. So we either need to find a way to stop that, or revert the PR in kata until we can fix in in tomlq. I think the net outcome is that this is a kata defect related to https://github.com/kata-containers/kata-containers/pull/8639/files and so should be raised as a kata issue.

Bingo! Great Steve!

**Comment by beraldoleal** [comment] 2023-12-14 20:27
> hmmm maybe... @beraldoleal found a bug (and fix) on containerd regarding a conversion from int to float too. @beraldoleal could you share the link? But it might be an old bug on another piece of containerd's code...

@wainersm you mean this bug? :)

**Comment by stevenhorsman** [comment] 2023-12-15 11:28
I've raised https://github.com/kata-containers/kata-containers/issues/8678 in kata-containers to track this issue.

**Comment by stevenhorsman** [comment] 2023-12-19 09:42
I'm not super happy with https://github.com/kata-containers/kata-containers/pull/8679 as I feel like the test of containerd being corrupted could be improved, but it passes the required kata-containers tests and when testing that payload with the operator it seems to be working:
```
INFO: Running operator tests for kata-qemu
operator_tests.bats
 ✓ [cc][operator] Test can uninstall the operator
 ✓ [cc][operator] Test can reinstall the operator

2 tests, 0 failures
```
where
```
$ kubectl describe pod cc-operator-daemon-install-6dqcg -n confidential-containers-system | grep image
  Normal  Pulling    14m   kubelet            Pulling image "ghcr.io/kata-containers/kata-deploy-ci:8679-c6b9f86a6f06d3ebd9db2cfee309ab8be7e5686a-amd64"
  Normal  Pulled     14m   kubelet            Successfully pulled image "ghcr.io/kata-containers/kata-deploy-ci:8679-c6b9f86a6f06d3ebd9db2cfee309ab8be7e5686a-amd64" in 657.693131ms
```

And after this:
```
$ cat /etc/containerd/config.toml | grep 'kata\|sampling'
    sampling_ratio = 1.0
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-clh]
  runtime_type = "io.containerd.kata-clh.v2"
  pod_annotations = ["io.katacontainers.*"]
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-clh.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers//configuration-clh.toml"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu]
  runtime_type = "io.containerd.kata-qemu.v2"
  pod_annotations = ["io.katacontainers.*"]
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers//configuration-qemu.toml"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu-tdx]
  runtime_type = "io.containerd.kata-qemu-tdx.v2"
  pod_annotations = ["io.katacontainers.*"]
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu-tdx.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers//configuration-qemu-tdx.toml"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu-sev]
  runtime_type = "io.containerd.kata-qemu-sev.v2"
  pod_annotations = ["io.katacontainers.*"]
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu-sev.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers//configuration-qemu-sev.toml"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu-snp]
  runtime_type = "io.containerd.kata-qemu-snp.v2"
  pod_annotations = ["io.katacontainers.*"]
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-qemu-snp.options]
    ConfigPath = "/opt/kata/share/defaults/kata-containers//configuration-qemu-snp.toml"
```
Showing that it injected the kata config, without corrupting the sampling_ratio.

Based on this, I think that temporary revert is good enough to fix the operator until next year when more people get back and we can have a proper think. I do need another green tick to merge it though. @BbolroC - maybe you could have a review if you feel comfortable?

**Comment by fidencio** [comment] 2023-12-26 10:31
I'm closing this one as we've fixed it on the Kata Containers side with https://github.com/kata-containers/kata-containers/pull/8709, feel free to re-open in case you face it again, and send us a ping on Slack so we become aware of this sooner than later.

**Closed by fidencio** 2023-12-26 10:31 UTC
